require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.lsp")

-- Plugin configs
require("user.alpha")
require("user.autocommands")
require("user.autopairs")
--require("user.bufferline")
require("user.cmp")
require("user.colorscheme")
require("user.colorizer")
require("user.gitsigns")
require("user.impatient")
require("user.lualine")
require("user.nvim-tree")
require("user.nvim-r")
require("user.telescope")
require("user.treesitter")

