require("user.options")
require("user.keymaps")
require("user.lazy")
require("user.mason")

-- Require plugins options
require("user.alpha")
require("user.autopairs")
require("user.bufferline")
require("user.cmp")
require("user.colorscheme")
require("user.gitsigns")
require("user.indentline")
require("user.lualine")
require("user.lsp-signature")
require("user.markdown_prev")
require("user.nvim-r")
require("user.nvimtree")
require("user.telescope")
require("user.treesitter")
require("user.trouble")
require("user.vimtex")
